import type { Chain } from '@/types/chain';

export const CHAINS: Chain[] = [
	{
		name: 'Ethereum',
		id: 1,
		image: 'https://icons.llamao.fi/icons/chains/rsz_ethereum.jpg',
		layerzeroId: 30101,
		mayanId: 2,
	},
	{
		name: 'Optimism',
		id: 10,
		image: 'https://icons.llamao.fi/icons/chains/rsz_optimism.jpg',
		layerzeroId: 30111,
		mayanId: 24,
	},
	{
		name: 'BSC',
		id: 56,
		image: 'https://icons.llamao.fi/icons/chains/rsz_binance.jpg',
		layerzeroId: 30102,
		mayanId: 4,
	},
	{
		name: 'Polygon',
		id: 137,
		image: 'https://icons.llamao.fi/icons/chains/rsz_polygon.jpg',
		layerzeroId: 30109,
		mayanId: 5,
	},
	{
		name: 'Sonic',
		id: 146,
		image: 'https://icons.llamao.fi/icons/chains/rsz_sonic.jpg',
		layerzeroId: 30332,
	},
	{
		name: 'Fantom',
		id: 250,
		image: 'https://icons.llamao.fi/icons/chains/rsz_fantom.jpg',
		layerzeroId: 30112,
	},
	{
		name: 'Fraxtal',
		id: 252,
		image: 'https://icons.llamao.fi/icons/chains/rsz_fraxtal.jpg',
		layerzeroId: 30255,
	},
	{
		name: 'ZkSync Era',
		id: 324,
		image: 'https://icons.llamao.fi/icons/chains/rsz_zksync%20era.jpg',
		layerzeroId: 30165,
	},
	{
		name: 'Mantle',
		id: 5000,
		image: 'https://icons.llamao.fi/icons/chains/rsz_mantle.jpg',
		layerzeroId: 30181,
	},
	{
		name: 'Base',
		id: 8453,
		image: 'https://icons.llamao.fi/icons/chains/rsz_base.jpg',
		layerzeroId: 30184,
		mayanId: 30,
	},
	{
		name: 'Mode',
		id: 34443,
		image:
			'https://pbs.twimg.com/profile_images/1688569679877390338/IYXD4bdy_400x400.jpg',
		layerzeroId: 30260,
	},
	{
		name: 'Arbitrum',
		id: 42161,
		image: 'https://icons.llamao.fi/icons/chains/rsz_arbitrum.jpg',
		layerzeroId: 30110,
		mayanId: 23,
	},
	{
		name: 'Avalanche',
		id: 43114,
		image: 'https://icons.llamao.fi/icons/chains/rsz_avalanche.jpg',
		layerzeroId: 30106,
		mayanId: 6,
	},
	{
		name: 'Linea',
		id: 59144,
		image: 'https://icons.llamao.fi/icons/chains/rsz_linea.jpg',
		layerzeroId: 30183,
	},
	{
		name: 'Scroll',
		id: 534352,
		image: 'https://icons.llamao.fi/icons/chains/rsz_scroll.jpg',
		layerzeroId: 30214,
	},
	{
		name: 'Berachain bArtio',
		id: 80084,
		image:
			'https://pbs.twimg.com/profile_images/1775162753499508736/2XBUzQhl_400x400.jpg',
		layerzeroId: 40291,
	},
	{
		name: 'Blast',
		id: 81457,
		image: 'https://icons.llamao.fi/icons/chains/rsz_blast.jpg',
		layerzeroId: 30243,
	},
	{
		name: 'Taiko',
		id: 167000,
		image: 'https://icons.llamao.fi/icons/chains/rsz_taiko.jpg',
		layerzeroId: 30290,
	},
	{
		name: 'Manta',
		id: 169,
		image: 'https://icons.llamao.fi/icons/chains/rsz_manta.jpg',
		layerzeroId: 30217,
	},
	{
		name: 'Celo',
		id: 42220,
		image: 'https://icons.llamao.fi/icons/chains/rsz_celo.jpg',
		layerzeroId: 30125,
	},
	{
		name: 'Gnosis',
		id: 100,
		image: 'https://icons.llamao.fi/icons/chains/rsz_gnosis.jpg',
		layerzeroId: 30145,
	},
	{
		name: 'Moonbeam',
		id: 1284,
		image: 'https://icons.llamao.fi/icons/chains/rsz_moonbeam.jpg',
		layerzeroId: 30126,
	},
	{
		name: 'Eclipse',
		id: 1408864445,
		image:
			'https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/chains/eclipsemainnet/logo.svg',
	},
	{
		name: 'Solana',
		id: 1399811149,
		image:
			'https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/chains/solanamainnet/logo.svg',
		layerzeroId: 30168,
		mayanId: 1,
		jumperId: 1151111081099710,
	},
	{
		name: 'Neutron',
		id: 1853125230,
		image:
			'https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/chains/neutron/logo.svg',
	},
	{
		name: 'Aptos',
		image: 'https://explorer.mayan.finance/assets/aptos.png',
		mayanId: 22,
		layerzeroId: 30108,
	},
	{
		name: 'Gravity',
		image: 'https://icons.llamao.fi/icons/chains/rsz_gravity.jpg',
		id: 1625,
	},
	{
		name: 'ZkFair',
		image: 'https://cdn.orbiter.finance/icon/chain/42766.svg',
		id: 42766,
	},
	{
		name: 'Harmony',
		image: 'https://icons.llamao.fi/icons/chains/rsz_harmony.jpg',
		id: 1666600000,
		layerzeroId: 30116,
	},
	{
		name: 'Viction',
		image: 'https://icons.llamao.fi/icons/chains/rsz_tomochain.jpg',
		id: 88,
		layerzeroId: 30196,
	},
	{
		name: 'Fuse',
		image: 'https://icons.llamao.fi/icons/chains/rsz_fuse.jpg',
		id: 122,
		layerzeroId: 30138,
	},
	{
		name: 'Moonriver',
		image: 'https://icons.llamao.fi/icons/chains/rsz_moonriver.jpg',
		id: 1285,
		layerzeroId: 30167,
	},
	{
		name: 'Unichain',
		image: 'https://icons.llamao.fi/icons/chains/rsz_unichain.jpg',
		id: 130,
		layerzeroId: 30320,
	},
	{
		name: 'Ink',
		image: 'https://icons.llamao.fi/icons/chains/rsz_ink.jpg',
		id: 57073,
		layerzeroId: 30339,
	},
	{
		name: 'CoreDAO',
		image: 'https://icons.llamao.fi/icons/chains/rsz_core.jpg',
		id: 1116,
		layerzeroId: 30153,
	},
	{
		name: 'Kaia',
		image: 'https://icons.llamao.fi/icons/chains/rsz_klaytn.jpg',
		id: 8217,
		layerzeroId: 30150,
	},
];
