export const PROJECTS = [
	{
		name: 'LayerZero',
		image: '/layerzero.webp',
		path: '/checker/layerzero',
		twitter: 'https://x.com/LayerZero_Core',
		discord: 'https://discord.com/invite/ktbvm8Nkcr',
		hasDescription: true,
	},
	{
		name: 'Eclipse',
		image: '/eclipse.webp',
		path: '/checker/eclipse',
		twitter: 'https://x.com/eclipsefnd',
		discord: 'https://discord.com/invite/eclipse-fnd',
	},
	{
		name: 'Odos',
		image: '/odos.webp',
		path: '/checker/odos',
		twitter: 'https://x.com/odosprotocol',
		discord: 'https://discord.com/invite/odos',
	},
	{
		name: 'Bebop',
		image: '/bebop.webp',
		path: '/checker/bebop',
		twitter: 'https://x.com/bebop_dex',
		discord: 'https://discord.com/invite/bebop',
	},
	{
		name: 'Wormhole',
		image: '/wormhole.webp',
		path: '/checker/wormhole',
		twitter: 'https://x.com/wormhole',
		discord: 'https://discord.com/invite/wormholecrypto',
		isDisabled: true,
	},
	{
		name: 'Hyperlane',
		image: '/hyperlane.webp',
		path: '/checker/hyperlane',
		twitter: 'https://x.com/hyperlane',
		discord: 'https://discord.gg/invite/VK9ZUy3aTV',
		isDisabled: true,
	},
];
